# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

COPY .env.production .env.production

ENV NODE_ENV=production

# Build the Next.js app
RUN npm run build

# Expose the port the app runs on
EXPOSE 80

# Start the Next.js app
# CMD ["npm", "start"]
CMD ["sh", "-c", "PORT=80 npm start"]