export const inputFields = [
    {
        id: 1,
        type: 'select',
        placeholder: 'Select Leader',
        label: 'Leader',
        name: 'leader_code',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: false,
        options: [],
    },
    {
        id: 2,
        type: 'text',
        placeholder: 'Enter agent first and last name',
        label: 'Agent first and last name',
        name: 'agent_name',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: false,
    },
    {
        id: 3,
        type: 'text',
        placeholder: 'Enter agent employee code',
        label: 'Agent employee code',
        name: 'agent_employee_code',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: false,
    },
    {
        id: 4,
        type: 'text',
        placeholder: 'Enter agent transparent email',
        label: 'Agent transparent email',
        name: 'agent_email',
        pattern: '^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: false,
    },
    {
        id: 5,
        type: 'date',
        placeholder: 'Select coating date',
        label: 'Coaching date',
        name: 'coaching_date',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: false,
    },
    {
        id: 6,
        type: 'radio',
        placeholder: 'Select coaching type',
        label: 'Coaching type',
        name: 'coaching_type',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: false,
        options: [
            { id: 1, label: '1:1', value: '1:1' },
            { id: 2, label: 'Developmental', value: 'Developmental' },
            { id: 3, label: 'Follow up', value: 'Follow up' },
            { id: 4, label: 'Calibration', value: 'Calibration' },
            { id: 5, label: 'Goals setting', value: 'Goals setting' },
            { id: 6, label: 'Setting expectations', value: 'Setting expectations' },
            { id: 7, label: 'Verbal warning', value: 'Verbal warning' },
            { id: 8, label: 'Written warning', value: 'Written warning' },
            { id: 9, label: 'Final written warning', value: 'Final written warning' },
            { id: 10, label: 'PIP Follow up', value: 'PIP Follow up' },
            { id: 11, label: 'Weekly Coaching Plan Review', value: 'Weekly Coaching Plan Review' },
        ],
    },
    {
        id: 7,
        type: 'radio',
        placeholder: 'Select Metric / Coaching Root',
        label: 'Metric / Coaching Root',
        name: 'metric',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'coaching_type',
            operator: '!==',
            value: 'Weekly Coaching Plan Review',
        },
        options: [
            { id: 1, label: 'Adherence', value: 'Adherence' },
            { id: 2, label: 'AHT', value: 'AHT' },
            { id: 3, label: 'AI Adoption', value: 'AI Adoption' },
            { id: 4, label: 'Attendance', value: 'Attendance' },
            { id: 5, label: 'Conversion', value: 'Conversion' },
            { id: 6, label: 'CSAT', value: 'CSAT' },
            { id: 7, label: 'De - Escalation', value: 'De - Escalation' },
            { id: 8, label: 'HGV Transfer', value: 'HGV Transfer' },
            { id: 9, label: 'LEAP', value: 'LEAP' },
            { id: 10, label: 'Lodge transfer', value: 'Lodge transfer' },
            { id: 11, label: 'Revenue per call', value: 'Revenue per call' },
            { id: 12, label: 'Proper Process Adherence', value: 'Proper Process Adherence' },
            { id: 13, label: 'Company policies', value: 'Company policies' },
            { id: 14, label: 'Professionalism', value: 'Professionalism' },
        ],
    },
    {
        id: 81,
        type: 'radio',
        placeholder: 'Select Indicator',
        label: 'Adherence — Behavioral Indicators',
        name: 'adherence_behavioral_indicator',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'metric',
            operator: '===',
            value: 'Adherence',
        },
        options: [
            {
                id: 1,
                label: 'Failure to follow assigned schedule',
                value: 'Failure to follow assigned schedule',
            },
            {
                id: 2,
                label: 'Logging in late / logging out early',
                value: 'Logging in late / logging out early',
            },
            {
                id: 3,
                label: 'Extended or unauthorized breaks',
                value: 'Extended or unauthorized breaks',
            },
            {
                id: 4,
                label: 'Not returning from breaks on time',
                value: 'Not returning from breaks on time',
            },
            { id: 5, label: 'Poor time-management habits', value: 'Poor time-management habits' },
            { id: 6, label: 'Ignoring schedule reminders', value: 'Ignoring schedule reminders' },
            { id: 7, label: 'Positive feedback', value: 'Positive feedback' },
            { id: 8, label: 'Other', value: 'Other' },
        ],
    },
    {
        id: 82,
        type: 'radio',
        placeholder: 'Select Indicator',
        label: 'AHT (Average Handle Time) — Behavioral Indicators',
        name: 'aht_behavioral_indicator',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'metric',
            operator: '===',
            value: 'AHT',
        },
        options: [
            {
                id: 1,
                label: 'Over-talking or unnecessary conversation',
                value: 'Over-talking or unnecessary conversation',
            },
            { id: 2, label: 'Inefficient call flow', value: 'Inefficient call flow' },
            { id: 3, label: 'Slow system navigation', value: 'Slow system navigation' },
            {
                id: 4,
                label: 'Long holds due to poor organization',
                value: 'Long holds due to poor organization',
            },
            {
                id: 5,
                label: 'Repeating questions already answered',
                value: 'Repeating questions already answered',
            },
            { id: 6, label: 'Lack of call control', value: 'Lack of call control' },
            { id: 7, label: 'Positive feedback', value: 'Positive feedback' },
            { id: 8, label: 'Other', value: 'Other' },
        ],
    },
    {
        id: 83,
        type: 'radio',
        placeholder: 'Select Indicator',
        label: 'AI Adoption — Behavioral Indicators',
        name: 'ai_adoption_behavioral_indicator',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'metric',
            operator: '===',
            value: 'AI Adoption',
        },
        options: [
            { id: 1, label: 'Not using required AI tools', value: 'Not using required AI tools' },
            {
                id: 2,
                label: 'Ignoring AI prompts or suggestions',
                value: 'Ignoring AI prompts or suggestions',
            },
            { id: 3, label: 'Resistance to new technology', value: 'Resistance to new technology' },
            {
                id: 4,
                label: 'Poor interaction with AI workflow',
                value: 'Poor interaction with AI workflow',
            },
            {
                id: 5,
                label: 'Overdependence or underutilization of AI features',
                value: 'Overdependence or underutilization of AI features',
            },
            { id: 6, label: 'Positive feedback', value: 'Positive feedback' },
            { id: 7, label: 'Other', value: 'Other' },
        ],
    },
    {
        id: 84,
        type: 'radio',
        placeholder: 'Select Indicator',
        label: 'Attendance — Behavioral Indicators',
        name: 'attendance_behavioral_indicator',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'metric',
            operator: '===',
            value: 'Attendance',
        },
        options: [
            { id: 1, label: 'Frequent tardiness', value: 'Frequent tardiness' },
            { id: 2, label: 'Unplanned absences', value: 'Unplanned absences' },
            {
                id: 3,
                label: 'Pattern of last-minute call-outs',
                value: 'Pattern of last-minute call-outs',
            },
            {
                id: 4,
                label: 'Failure to follow attendance procedures',
                value: 'Failure to follow attendance procedures',
            },
            {
                id: 5,
                label: 'Poor responsibility for shift commitments',
                value: 'Poor responsibility for shift commitments',
            },
            { id: 6, label: 'Positive feedback', value: 'Positive feedback' },
            { id: 7, label: 'Other', value: 'Other' },
        ],
    },
    {
        id: 85,
        type: 'radio',
        placeholder: 'Select Indicator',
        label: 'Conversion — Behavioral Indicators',
        name: 'conversion_behavioral_indicator',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'metric',
            operator: '===',
            value: 'Conversion',
        },
        options: [
            { id: 1, label: 'Weak pitch delivery', value: 'Weak pitch delivery' },
            {
                id: 2,
                label: 'Not offering products/services consistently',
                value: 'Not offering products/services consistently',
            },
            { id: 3, label: 'Poor objection handling', value: 'Poor objection handling' },
            { id: 4, label: 'Missing buying signals', value: 'Missing buying signals' },
            {
                id: 5,
                label: 'Lack of confidence during sales conversation',
                value: 'Lack of confidence during sales conversation',
            },
            { id: 6, label: 'Not personalizing the offer', value: 'Not personalizing the offer' },
            { id: 7, label: 'Positive feedback', value: 'Positive feedback' },
            { id: 8, label: 'Other', value: 'Other' },
        ],
    },
    {
        id: 86,
        type: 'radio',
        placeholder: 'Select Indicator',
        label: 'CSAT — Behavioral Indicators',
        name: 'behavioral_indicator',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'metric',
            operator: '===',
            value: 'CSAT',
        },
        options: [
            { id: 1, label: 'Low empathy', value: 'Low empathy' },
            {
                id: 2,
                label: 'Failure to acknowledge the customer',
                value: 'Failure to acknowledge the customer',
            },
            {
                id: 3,
                label: 'Robotic or non-engaging communication',
                value: 'Robotic or non-engaging communication',
            },
            { id: 4, label: 'Negative or indifferent tone', value: 'Negative or indifferent tone' },
            { id: 5, label: 'Not resolving the root issue', value: 'Not resolving the root issue' },
            { id: 6, label: 'Rushing the customer', value: 'Rushing the customer' },
            { id: 7, label: 'Positive feedback', value: 'Positive feedback' },
            { id: 8, label: 'Other', value: 'Other' },
        ],
    },
    {
        id: 87,
        type: 'radio',
        placeholder: 'Select Indicator',
        label: 'De - Escalation — Behavioral Indicators',
        name: 'de_escalation_behavioral_indicator',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'metric',
            operator: '===',
            value: 'De - Escalation',
        },
        options: [
            { id: 1, label: 'Escalating unnecessarily', value: 'Escalating unnecessarily' },
            {
                id: 2,
                label: 'Not attempting first-contact resolution',
                value: 'Not attempting first-contact resolution',
            },
            { id: 3, label: 'Lack of ownership', value: 'Lack of ownership' },
            { id: 4, label: 'Poor de-escalation behavior', value: 'Poor de-escalation behavior' },
            {
                id: 5,
                label: 'Not following escalation protocol',
                value: 'Not following escalation protocol',
            },
            { id: 6, label: 'Positive feedback', value: 'Positive feedback' },
            { id: 7, label: 'Other', value: 'Other' },
        ],
    },
    {
        id: 88,
        type: 'radio',
        placeholder: 'Select Indicator',
        label: 'HGV Transfer — Behavioral Indicators',
        name: 'hgv_transfer_behavioral_indicator',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'metric',
            operator: '===',
            value: 'HGV Transfer',
        },
        options: [
            {
                id: 1,
                label: 'Fails to offer the HGV transfer even when customer is eligible',
                value: 'Fails to offer the HGV transfer even when customer is eligible',
            },
            {
                id: 2,
                label: 'Provides a weak or unclear explanation of the HGV program',
                value: 'Provides a weak or unclear explanation of the HGV program',
            },
            {
                id: 3,
                label: 'Avoids offering the transfer due to lack of confidence',
                value: 'Avoids offering the transfer due to lack of confidence',
            },
            {
                id: 4,
                label: 'Shows hesitation or discomfort during the pitch',
                value: 'Shows hesitation or discomfort during the pitch',
            },
            {
                id: 5,
                label: 'Does not follow the required HGV transfer workflow',
                value: 'Does not follow the required HGV transfer workflow',
            },
            {
                id: 6,
                label: 'Uses monotone or low-engagement tone when presenting the transfer',
                value: 'Uses monotone or low-engagement tone when presenting the transfer',
            },
            {
                id: 7,
                label: 'Appears uninterested or disengaged when discussing the program',
                value: 'Appears uninterested or disengaged when discussing the program',
            },
            { id: 8, label: 'Positive feedback', value: 'Positive feedback' },
            { id: 9, label: 'Other', value: 'Other' },
        ],
    },
    {
        id: 89,
        type: 'radio',
        placeholder: 'Select Indicator',
        label: 'LEAP — Behavioral Indicators',
        name: 'leap_behavioral_indicator',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'metric',
            operator: '===',
            value: 'LEAP',
        },
        options: [
            { id: 1, label: 'Did not actively listen', value: 'Did not actively listen' },
            { id: 2, label: 'Interrupted the customer', value: 'Interrupted the customer' },
            { id: 3, label: 'Missed key information', value: 'Missed key information' },
            { id: 4, label: 'Responded irrelevantly', value: 'Responded irrelevantly' },
            { id: 5, label: 'Weak empathy statements', value: 'Weak empathy statements' },
            { id: 6, label: 'Robotic or scripted empathy', value: 'Robotic or scripted empathy' },
            { id: 7, label: 'Poor tone / lack of warmth', value: 'Poor tone / lack of warmth' },
            { id: 8, label: 'Insufficient probing', value: 'Insufficient probing' },
            {
                id: 9,
                label: 'Asked irrelevant/repetitive questions',
                value: 'Asked irrelevant/repetitive questions',
            },
            {
                id: 10,
                label: 'Failed to clarify key details',
                value: 'Failed to clarify key details',
            },
            { id: 11, label: 'Incomplete resolution', value: 'Incomplete resolution' },
            { id: 12, label: 'Incorrect solution', value: 'Incorrect solution' },
            {
                id: 13,
                label: 'Poor explanation of next steps',
                value: 'Poor explanation of next steps',
            },
            { id: 14, label: 'Positive feedback', value: 'Positive feedback' },
            { id: 15, label: 'Other', value: 'Other' },
        ],
    },
    {
        id: 90,
        type: 'radio',
        placeholder: 'Select Indicator',
        label: 'Lodge Transfer — Behavioral Indicators',
        name: 'lodge_transfer_behavioral_indicator',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'metric',
            operator: '===',
            value: 'Lodge transfer',
        },
        options: [
            { id: 1, label: 'Incorrect routing', value: 'Incorrect routing' },
            {
                id: 2,
                label: 'Incomplete customer information before transfer',
                value: 'Incomplete customer information before transfer',
            },
            {
                id: 3,
                label: 'Not confirming transfer reason',
                value: 'Not confirming transfer reason',
            },
            { id: 4, label: 'Poor handoff etiquette', value: 'Poor handoff etiquette' },
            {
                id: 5,
                label: 'Failure to minimize customer effort',
                value: 'Failure to minimize customer effort',
            },
            { id: 6, label: 'Cold transferred', value: 'Cold transferred' },
            { id: 7, label: 'Positive feedback', value: 'Positive feedback' },
            { id: 8, label: 'Other', value: 'Other' },
        ],
    },
    {
        id: 91,
        type: 'radio',
        placeholder: 'Select Indicator',
        label: 'Revenue per Call — Behavioral Indicators',
        name: 'revenue_per_call_behavioral_indicator',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'metric',
            operator: '===',
            value: 'Revenue per call',
        },
        options: [
            { id: 1, label: 'No upsell/cross-sell attempt', value: 'No upsell/cross-sell attempt' },
            { id: 2, label: 'Weak discovery questions', value: 'Weak discovery questions' },
            { id: 3, label: 'Not highlighting value', value: 'Not highlighting value' },
            {
                id: 4,
                label: 'Missing opportunities for add-ons',
                value: 'Missing opportunities for add-ons',
            },
            {
                id: 5,
                label: 'Focusing only on resolution without exploring sales',
                value: 'Focusing only on resolution without exploring sales',
            },
            { id: 6, label: 'Positive feedback', value: 'Positive feedback' },
            { id: 7, label: 'Other', value: 'Other' },
        ],
    },
    {
        id: 92,
        type: 'radio',
        placeholder: 'Select Indicator',
        label: 'Proper Process Adherence — Behavioral Indicators',
        name: 'proper_process_adherence_behavioral_indicator',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'metric',
            operator: '===',
            value: 'Proper Process Adherence',
        },
        options: [
            {
                id: 1,
                label: 'Skipping required steps in workflow',
                value: 'Skipping required steps in workflow',
            },
            { id: 2, label: 'Not following SOPs', value: 'Not following SOPs' },
            { id: 3, label: 'Improper documentation', value: 'Improper documentation' },
            { id: 4, label: 'Incorrect use of systems', value: 'Incorrect use of systems' },
            {
                id: 5,
                label: 'Deviating from standard call flow',
                value: 'Deviating from standard call flow',
            },
            {
                id: 6,
                label: 'Improper validation or disclosure',
                value: 'Improper validation or disclosure',
            },
            { id: 7, label: 'Positive feedback', value: 'Positive feedback' },
            { id: 8, label: 'Other', value: 'Other' },
        ],
    },
    {
        id: 93,
        type: 'radio',
        placeholder: 'Select Indicator',
        label: 'Company Policies — Behavioral Indicators',
        name: 'company_policies_behavioral_indicator',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'metric',
            operator: '===',
            value: 'Company policies',
        },
        options: [
            {
                id: 1,
                label: 'Failure to comply with internal rules',
                value: 'Failure to comply with internal rules',
            },
            { id: 2, label: 'Misuse of tools or systems', value: 'Misuse of tools or systems' },
            {
                id: 3,
                label: 'Inappropriate workplace behavior',
                value: 'Inappropriate workplace behavior',
            },
            {
                id: 4,
                label: 'Ignoring data protection guidelines',
                value: 'Ignoring data protection guidelines',
            },
            {
                id: 5,
                label: 'Not following communication standards',
                value: 'Not following communication standards',
            },
            { id: 6, label: 'Positive feedback', value: 'Positive feedback' },
            { id: 7, label: 'Sales Integrity', value: 'Sales Integrity' },
            { id: 8, label: 'Work avoidance', value: 'Work avoidance' },
            { id: 9, label: 'Other', value: 'Other' },
        ],
    },
    {
        id: 94,
        type: 'radio',
        placeholder: 'Select Indicator',
        label: 'Professionalism — Behavioral Indicators',
        name: 'professionalism_behavioral_indicator',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            field: 'metric',
            operator: '===',
            value: 'Professionalism',
        },
        options: [
            {
                id: 1,
                label: 'Unprofessional language or tone',
                value: 'Unprofessional language or tone',
            },
            { id: 2, label: 'Lack of courtesy', value: 'Lack of courtesy' },
            {
                id: 3,
                label: 'Poor attitude toward customers or teammates',
                value: 'Poor attitude toward customers or teammates',
            },
            {
                id: 4,
                label: 'Not maintaining a professional demeanor',
                value: 'Not maintaining a professional demeanor',
            },
            { id: 5, label: 'Resistance toward feedback', value: 'Resistance toward feedback' },
            {
                id: 6,
                label: 'Displaying negative or disruptive behavior',
                value: 'Displaying negative or disruptive behavior',
            },
            { id: 7, label: 'Positive feedback', value: 'Positive feedback' },
            { id: 8, label: 'Other', value: 'Other' },
        ],
    },
    {
        id: 9,
        type: 'textarea',
        placeholder: 'Enter coaching comments',
        label: 'Coaching comments',
        name: 'coaching_comments',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            operator: 'OR',
            conditions: [
                {
                    field: 'coaching_type',
                    operator: '===',
                    value: 'Weekly Coaching Plan Review',
                },
                {
                    field: 'metric',
                    operator: 'notEmpty',
                    value: true,
                },
            ],
        },
    },
    {
        id: 10,
        type: 'textarea',
        placeholder: 'Enter strengths',
        label: 'Strengths',
        name: 'strengths',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            operator: 'OR',
            conditions: [
                {
                    field: 'coaching_type',
                    operator: '===',
                    value: 'Weekly Coaching Plan Review',
                },
                {
                    field: 'metric',
                    operator: 'notEmpty',
                    value: true,
                },
            ],
        },
    },
    {
        id: 11,
        type: 'textarea',
        placeholder: 'Enter opportunities',
        label: 'Opportunities',
        name: 'opportunities',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            operator: 'OR',
            conditions: [
                {
                    field: 'coaching_type',
                    operator: '===',
                    value: 'Weekly Coaching Plan Review',
                },
                {
                    field: 'metric',
                    operator: 'notEmpty',
                    value: true,
                },
            ],
        },
    },
    {
        id: 12,
        type: 'textarea',
        placeholder: 'Enter action plan',
        label: 'Action plan',
        name: 'action_plan',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            operator: 'OR',
            conditions: [
                {
                    field: 'coaching_type',
                    operator: '===',
                    value: 'Weekly Coaching Plan Review',
                },
                {
                    field: 'metric',
                    operator: 'notEmpty',
                    value: true,
                },
            ],
        },
    },
    {
        id: 13,
        type: 'upload file',
        placeholder: 'Upload files',
        label: 'Coaching related attachments',
        name: 'coaching_related_attachments',
        required: false,
        disabled: false,
        readOnly: false,
        hidden: true,
        allowedExtensions: [
            '.doc',
            '.docx',
            '.xls',
            '.xlsx',
            '.ppt',
            '.pptx',
            '.pdf',
            'image/*',
            'video/*',
            'audio/*',
        ],
        maxFiles: 3,
        maxFileSizeMB: 100,
        dependsOn: {
            operator: 'OR',
            conditions: [
                {
                    field: 'coaching_type',
                    operator: '===',
                    value: 'Weekly Coaching Plan Review',
                },
                {
                    field: 'metric',
                    operator: 'notEmpty',
                    value: true,
                },
            ],
        },
    },
    {
        id: 14,
        type: 'textarea',
        placeholder: 'Enter leader commitment',
        label: 'Leader commitment',
        name: 'leader_commitment',
        required: true,
        disabled: false,
        readOnly: false,
        hidden: true,
        dependsOn: {
            operator: 'OR',
            conditions: [
                {
                    field: 'coaching_type',
                    operator: '===',
                    value: 'Weekly Coaching Plan Review',
                },
                {
                    field: 'metric',
                    operator: 'notEmpty',
                    value: true,
                },
            ],
        },
    },
]
