export const REPORT_TYPES = [{ value: 'horas.inconsistencias', label: 'Horas Inconsistencias' }]

export const TIPOS_DESCONEXION = [
    { value: '', label: 'Seleccionar opción' },
    { value: 'QA Feedback', label: 'QA Feedback' },
    { value: 'Sanction Signature', label: 'Sanction Signature' },
    { value: 'Avaya License Issues', label: 'Avaya License Issues' },
    { value: 'Shift Change Notification', label: 'Shift Change Notification' },
    { value: 'HR Audience', label: 'HR Audience' },
    { value: 'Feedback', label: 'Feedback' },
    { value: 'Horas Extras en Mentoring', label: 'Horas Extras en Mentoring' },
    { value: 'Mentor', label: 'Mentor' },
    { value: 'Asueto Internacional', label: 'Asueto Internacional' },
    { value: 'Missing Time IAK', label: 'Missing Time IAK' },
    { value: 'Login Issues', label: 'Login Issues' },
    { value: 'Problemas de Licencias', label: 'Problemas de Licencias' },
    { value: 'Retroalimentación', label: 'Retroalimentación' },
    { value: 'Balance', label: 'Balance' },
    { value: 'Overlap', label: 'Overlap' },
    { value: 'Notificación PIP', label: 'Notificación PIP' },
    { value: 'Notificación Cambio de Turno', label: 'Notificación Cambio de Turno' },
    { value: 'Audiencia HR', label: 'Audiencia HR' },
    { value: 'Caida del Sistema', label: 'Caida del Sistema' },
    { value: 'Desconexión QA', label: 'Desconexión QA' },
    { value: 'Capacitaciones', label: 'Capacitaciones' },
    { value: 'Solicitud de Mentor', label: 'Solicitud de Mentor' },
    { value: 'IAK', label: 'IAK' },
    { value: 'Mentor, Capa, Prom y Shadow', label: 'Mentor, Capa, Prom y Shadow' },
    { value: '0-30 Días', label: '0-30 Días' },
    { value: 'Sin Sistema', label: 'Sin Sistema' },
    { value: 'Breastfeeding', label: 'Breastfeeding' },
]
