export { attendanceApi } from './attendance.api'
export { awsOperationApi } from './aws.operation.api'
export { catalogsApi } from './catalogs.api'
export { catalogshrApi } from './catalogshr.api'
export { generationApi } from './generation.api'
export { uadApi } from './uad.api'
export { baseURL } from './baseURL'
